version: '3.8'
services: 
  postgres:
    image: postgres:16
    container_name: teste
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: Teste1
    volumes:
      - postgres_data:/var/lib/postgressql/postgres_data

volumes:
  postgres_data: